export const programOptions: string[] = [
    '',
  "Science",
  "Business",
  "Accounting",
  "Music",
  "Food Science",
  "Education",
  "Sports",
  "Agriculture",
  "Finance",
  "Arts",
  "Languages",
  "Environment",
  "History",
  "Sales",
  "Technology",
  "Graphic Design",
  "Performing Arts",
  "Sociology",
  "Advertising",
  "Health",
  "Marketing",
  "Communications",
  "Public Relations",
  "Psychology",
  "Engineering",
  "Anthropology",
  "Literature",
  "Fashion",
  "Nutrition",
  "Event Planning",
  "Linguistic",
  "Animals",
  "Data Analysis",
  "Politics",
  "Social",
  "Drama",
  "Fitness",
  "Journalism",
  "Cooking",
  "Plants",
  "Photography",
  "Humanities",
  "Art",
  "Medical",
  "Travel",
];

export const team: {
  name: string;
  role: string;
  img?: string;
}[] = [
  {
    name: "Christian Abrokwa",
    role: "Software Engineer",
    img: "/DIA_Group_Images/Christian Abrokwa.jpeg",
  },
  {
    name: "Kofi Yeboah",
    role: "Graphic Designer",
    img: "/DIA_Group_Images/Kofi Yeboah.jpeg",
  },
  {
    name: "Mersharch Demenya",
    role: "Software Developer",
  },
  {
    name: "Joseph Ampadu",
    role: "Software Developer",
    img: "/DIA_Group_Images/Joseph Ampadu.jpeg",
  },
  {
    name: "Solomon Nnyamile",
    role: "Software Engineer",
    img: "/DIA_Group_Images/Solomon Yaw.jpeg",
  },
  {
    name: "Samuel Sackey",
    role: "Software Engineer",
    img: "/DIA_Group_Images/Samuel Sackey.jpeg",
  },
  {
    name: "Kingsley Acquah",
    role: "Software Developer",
    img: "/DIA_Group_Images/Kingsley Acquah.jpeg",
  },
  {
    name: "Gideon  Agyei",
    role: "UI/UX Desginer",
    img: "/DIA_Group_Images/Gideon Agyei.jpeg",
  },
  {
    name: "Prince Gyan",
    role: "Software Engineer",
    img: "/DIA_Group_Images/Prince Jan.jpeg",
  },
  {
    name: "Kelvin  Abadang",
    role: "Software Developer",
    img: "/DIA_Group_Images/Kelvin Abadang.jpeg",
  },
  {
    name: "Manasseh Sandy",
    role: "Software Engineer",
    img: "/DIA_Group_Images/Manasseh Sandy.jpeg",
  },
];

export const dream_job: string[] = [
    '',
  "Research and Development Scientist",
  "Chief Executive Officer (CEO)",
  "Oceanographer",
  "Accountant",
  "Failure Analysis Engineer",
  "Musician",
  "Manufacturing Manager",
  "Art Teacher",
  "Sports Nutritionist",
  "Human Resources Manager",
  "Soil Scientist",
  "Business Development Manager",
  "Stockbroker",
  "Surgeon",
  "Art Director",
  "Education Administrator",
  "Dancer",
  "Foreign Language Teacher",
  "Seismologist",
  "Aquaculture Farmer",
  "Investment Banker",
  "Clinical Psychologist",
  "Museum Curator",
  "Sales Representative",
  "Bioprocessing Engineer",
  "Mobile Applications Developer",
  "Financial Analyst",
  "IT Manager",
  "Consumer Psychologist",
  "Anesthesiologist",
  "Neurosurgeon",
  "General Practitioner",
  "Graphic Designer",
  "Chemist",
  "Occupational Therapist",
  "Cloud Architect",
  "IT Systems Security Manager",
  "User Experience Designer",
  "Data Scientist",
  "Actor",
  "Social and Community Service Mgr",
  "Advertising Copywriter",
  "Emergency Medicine Physician",
  "Petroleum Geologist",
  "Respiratory Therapist",
  "Brand Manager",
  "Chief Operating Officer (COO)",
  "Research and Development Manager",
  "Public Relations Specialist",
  "Neuropsychologist",
  "Nurse Anesthetist",
  "Teacher",
  "Research Scientist",
  "Education Consultant",
  "Blockchain Engineer",
  "Educational Psychologist",
  "Psychologist",
  "Computer Systems Analyst",
  "Project Manager",
  "Composite Materials Engineer",
  "Law Librarian",
  "Operations Manager",
  "Systems Analyst",
  "Database Administrator",
  "Cytotechnologist",
  "Epidemiologist",
  "Process Control Engineer",
  "Technical Support Specialist",
  "Anthropologist",
  "Business Intelligence Developer",
  "Nuclear Medicine Technologist",
  "Entrepreneur",
  "Writer",
  "Childcare Center Director",
  "Art Therapist",
  "Cyber Security Analyst",
  "Immigration Lawyer",
  "Hardware Design Engineer",
  "Software Architect",
  "Psychiatrist",
  "Textile Designer",
  "Fashion Designer",
  "Trauma Surgeon",
  "Network and Computer Systems Administrator",
  "Animal Behaviorist",
  "Market Research Analyst",
  "Application Analyst",
  "Business Intelligence Analyst",
  "Biomedical Equipment Technician",
  "Precision Agriculture Specialist",
  "Veterinary Technician",
  "Product Development Scientist",
  "Curriculum Specialist",
  "Dental Equipment Salesperson",
  "Orthopedic Surgeon",
  "Education Researcher",
  "Forensic Science Technician",
  "Midwife",
  "Robotics Engineer",
  "Cyber Security Engineer",
  "Pediatrician",
  "Sculptor",
  "Drug Safety Associate",
  "Registered Dietitian",
  "Event Planner",
  "Orthodontist",
  "Child Life Specialist",
  "Speech-language pathologist",
  "IT Project Manager",
  "Quality Control Technician",
  "Food Process Engineer",
  "Paleontologist",
  "Primary School Teacher",
  "Artificial Intelligence (AI) Engineer",
  "Agricultural Equipment Design Engineer",
  "Irrigation Engineer",
  "Pharmaceutical Sales Representative",
  "Public Health Dentist",
  "Information Security Analyst",
  "Women's Health Nurse Practitioner",
  "Agricultural Biotechnology Researcher",
  "Physician",
  "Medical Scientist",
  "Neurological Physical Therapist",
  "Research Laboratory Technician",
  "Zoologist",
  "Consultant",
  "Agricultural Economist",
  "Medical laboratory technician",
  "Data Security Analyst",
  "Small Business Owner",
  "Textbook Editor",
  "Data Analyst",
  "Advertising Manager",
  "Science Writer",
  "Phlebotomist",
  "Family Medicine Physician",
  "Mathematician",
  "Labor Lawyer",
  "Historian",
  "Educational Researcher",
  "Supply Chain Manager",
  "Special Education Teacher",
  "Veterinarian",
  "Medical Laboratory Technician",
  "Genetic Counselor",
  "School Counselor",
  "Radiographer",
  "Pharmaceutical Scientist",
  "Environmental Scientist",
  "Drama Teacher",
  "Dental Product Sales Representative",
  "Family Lawyer",
  "Environmental health and safety specialist",
  "Biomedical Engineer",
  "Pediatric Nurse",
  "Shelter Veterinarian",
  "Food Safety Specialist",
  "Full-Stack Developer",
  "Family Law Attorney",
  "Environmental Engineer",
  "Management Analyst",
  "Compounding Pharmacist",
  "Biomaterials Engineer",
  "Software Developer",
  "Physical Therapist",
  "Forensic Psychologist",
  "Plastic Surgeon",
  "Artificial Intelligence Engineer",
  "English Teacher",
  "Pediatric Dentist",
  "Radiologist",
  "Educational Administrator",
  "Geochemist",
  "Oral and Maxillofacial Surgeon",
  "Network Security Engineer",
  "Information Systems Security Manager",
  "Database Manager",
  "Pharmacy Technician",
  "Web Developer",
  "Dental Laboratory Technician",
  "Diagnostic Medical Sonographer",
  "Social Psychologist",
  "Medical Science Liaison",
  "Journalist",
  "Intellectual Property Lawyer",
  "Biomechanical Engineer",
  "Tax Manager",
  "Guidance Counselor",
  "Endocrinologist",
  "Orthopedic Physical Therapist",
  "Applications Architect",
  "Agricultural and Food Scientist",
  "Prosthodontist",
  "Music Teacher",
  "Dental Anesthesiologist",
  "Environmental Health and Safety Specialist",
  "Geriatric Physical Therapist",
  "Nutritionist",
  "Data Architect",
  "DevOps Engineer",
  "Medical Lab Technologist",
  "Materials Testing Technician",
  "Product Development Engineer",
  "Regulatory Affairs Specialist",
  "Product Manager",
  "Molecular Biology Technologist",
  "Marketing Manager",
  "Food Technologist",
  "Geologist",
  "Sports Journalist",
  "Culinary Nutritionist",
  "Science Policy Analyst",
  "Obstetrician and Gynecologist",
  "Volcanologist",
  "Dental Researcher",
  "Surgical Oncologist",
  "Law Firm Administrator",
  "Cardiothoracic Surgeon",
  "Environmental Lawyer",
  "Human Rights Advocate",
  "Sales Manager",
  "Dental Surgeon",
  "Infectious Disease Specialist",
  "Computer Programmer",
  "Pharmacist",
  "Teacher Trainer",
  "Genetic counselor",
  "Science Communicator",
  "Site Reliability Engineer",
  "Research scientist",
  "Packaging Engineer",
  "Public Relations Manager",
  "Pathologist Assistant",
  "Occupational therapist",
  "User Interface Designer",
  "Information Technology (IT) Manager",
  "Tutor",
  "Nurse Practitioner",
  "Big Data Engineer",
  "Instructional Designer",
  "Agricultural Engineer",
  "Lawyer",
  "Diagnostic Radiologic Technologist",
  "Botanist",
  "Sustainable Agriculture Specialist",
  "Education Program Manager",
  "Clinical Nurse Specialist",
  "Hydrologist",
  "Software Engineer",
  "Food Service Manager",
  "Laboratory Director",
  "Radiologic technologist",
  "Librarian",
  "Medical Device Sales Representative",
  "Radiation Therapist",
  "Social Worker",
  "Physical therapist",
  "Dietitian",
  "Software Test Engineer",
  "Materials Engineer",
  "Pediatric Surgeon",
  "Legal Secretary",
  "Actuary",
  "Statistician",
  "Food and Beverage Manager",
  "Pediatric Physical Therapist",
  "Metallurgist",
  "Culinary Chef",
  "Ophthalmologist",
  "Agricultural Business Manager",
  "Neonatal Nurse",
  "Clinical Pharmacist",
  "Sports Psychologist",
  "Research Psychologist",
  "Medical Geneticist",
  "Food Safety Inspector",
  "Photographer",
  "Clinical Laboratory Scientist",
  "Forensic Scientist",
  "Healthcare Administrator",
  "Judge",
  "Solutions Engineer",
  "Dental Practice Manager",
  "Soil and Water Conservationist",
  "Dental Consultant",
  "Medical Equipment Salesperson",
  "Application Developer",
  "Periodontist",
  "Curator",
  "Agricultural Sales Representative",
  "Director",
  "Sports Physical Therapist",
  "Astronomer",
  "Farm Manager",
  "Agricultural Inspector",
  "Junior High School Teacher",
  "Materials Scientist",
  "School Nurse",
  "Medical Imaging Technologist",
  "Information Technology Manager",
  "Legal Analyst",
  "Art Critic",
  "PACS Administrator",
  "Meteorologist",
  "School Librarian",
  "Ecologist",
  "Athletic Director",
  "Doula",
  "Nurse Midwife",
  "Artist",
  "Water Resource Engineer",
  "Online Instructor",
  "School Administrator",
  "Nutrition Education Coordinator",
  "IT Security Specialist",
  "Space Scientist",
  "Biomedical Research Scientist",
  "Quality Control Analyst",
  "Education Technology Specialist",
  "Chief Financial Officer (CFO)",
  "Regulatory Affairs Manager",
  "Food Scientist",
  "Veterinary Pathologist",
  "Real Estate Lawyer",
  "Obstetrician-gynecologist",
  "Corporate Lawyer",
  "Clinical Trial Manager",
  "Physicist",
  "Biophysicist",
  "Parent Educator",
  "Nanotechnologist",
  "Family Services Worker",
  "Development Operations Manager",
  "Family Therapist",
  "Animal Welfare Specialist",
  "Bioinformatics Analyst",
  "Painter",
  "Agricultural Production Manager",
  "Pharmacologist",
  "Wildlife Veterinarian",
  "Agricultural Systems Engineer",
  "Dietitian Technician",
  "Home Health Nurse",
  "Criminal Lawyer",
  "Animal Nutritionist",
  "Pharmacy Manager",
  "Science Educator",
  "Tax Lawyer",
  "Educational Content Writer",
  "Dental Hygienist",
  "Nurse Educator",
  "Nurse",
  "MRI Technologist",
  "Pathologist",
  "Head Teacher",
  "Physical Education Teacher",
  "Emergency Room Nurse",
  "Medical Writer",
  "Blood Bank Technologist",
  "Speech Pathologist",
  "Oncologist",
  "Medical Illustrator",
  "Cardiologist",
  "Education Blogger",
  "Sports Medicine Physician",
  "Neurologist",
  "School Principal",
  "Health Care Lawyer",
  "Adoption Counselor",
  "Education Policy Analyst",
  "Restaurant Manager",
  "Sports Analyst",
  "Endodontist",
  "Radiology Information Specialist",
  "Equine Veterinarian",
  "Personal Stylist",
  "Curriculum Designer",
  "Fashion Merchandiser",
  "Lecturer",
  "Education Journalist",
  "Critical Care Nurse",
  "Secondary School Teacher",
  "Histotechnologist",
  "Civil Rights Lawyer",
  "Oncology Nurse",
  "Dermatologist",
  "Sports Coach",
  "Food Critic",
  "Admissions Officer",
  "Software Engineering Manager",
  "Laboratory Animal Veterinarian",
];

export const learning_styles: string[] = [
    '',
  "Analytical",
  "Global",
  "Logical",
  "Reflective",
  "Auditory",
  "Visual",
  "Kinesthetic",
  "Social",
  "Verbal",
  "Tactile",
  "Sequential",
  "Naturalistic",
  "Linguistic",
  "Intercultural",
  "Spatial",
  "Solitary",
  "Interpersonal",
  "Musical",
  "Intuitive",
];

export const fav_sub: string[] = [
    "",
  "Physics",
  "Economics",
  "Business",
  "Mathematics",
  "English Language",
  "Chemistry",
  "Education",
  "Physical Education",
  "General Knowledge in Art",
  "Linguistics",
  "Creative Arts",
  "Psychology",
  "ICT",
  "Social Studies",
  "French",
  "Science",
  "History",
  "Biology",
  "Geography",
  "Computer Science",
  "Religious and Moral Education",
  "Agriculture Science",
  "Home Economics",
  "Theater Arts",
  "Physics",
  "Home Business Studies",
];
